### ISSUE TITLE
'DebugToolbarMiddleware' object has no attribute 'generate_server_timing_header'

### ISSUE THREAD

**Issue by PetrDlouhy** [djsutho/django-debug-toolbar-request-history#41]
With DDT 3.6.0 I got this error message:
```error
Internal Server Error: /
Traceback (most recent call last):
  File "/home/petr/.cache/pypoetry/virtualenvs/blenderkit-server-eqrfB9dY-py3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/petr/.cache/pypoetry/virtualenvs/blenderkit-server-eqrfB9dY-py3.10/lib/python3.10/site-packages/sentry_sdk/integrations/django/middleware.py", line 175, in __call__
    return f(*args, **kwargs)
  File "/home/petr/.cache/pypoetry/virtualenvs/blenderkit-server-eqrfB9dY-py3.10/lib/python3.10/site-packages/ddt_request_history/panels/request_history.py", line 67, in patched_middleware_call
    response = self.generate_server_timing_header(
AttributeError: 'DebugToolbarMiddleware' object has no attribute 'generate_server_timing_header'
```

Shown on any page as this:
![Snímek obrazovky_2022-09-23_17-16-40](https://user-images.githubusercontent.com/156755/191994920-cf04cd92-5e0a-4fb2-b072-b2b9a778cf5d.png)

**Comment by PetrDlouhy** [comment]
When testing various versions, the last working version of DDT is `3.2.4`. The `3.3.0` breaks `django-debug-toolbar-request-history`.

**Comment by PetrDlouhy** [comment]
Ah, I totally missed #40
